apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: taskfoo
  namespace: testns
spec:
  steps:
    - args:
        - -c
        - sleep 60
      command:
        - /bin/bash
      image: fedora
      name: build-sources
      resources: {}
